language: node_js
services: docker
cache:
  directories:
    - $HOME/.npm
notifications:
  email: true
node_js:
  - '10'
  - '12'
before_script:
  - yarn redis:up -- -d && sleep 10
script:
  - yarn ci
after_success:
  - if [ $TRAVIS_NODE_VERSION == '12' ]; then
  -  yarn release
  -  yarn coveralls
  - fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
